/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/conditions-generales-d-utilisation': RouteRecordInfo<'/conditions-generales-d-utilisation', '/conditions-generales-d-utilisation', Record<never, never>, Record<never, never>>,
    '/mentions-legales': RouteRecordInfo<'/mentions-legales', '/mentions-legales', Record<never, never>, Record<never, never>>,
    '/politique-de-confidentialite': RouteRecordInfo<'/politique-de-confidentialite', '/politique-de-confidentialite', Record<never, never>, Record<never, never>>,
    '/reglement': RouteRecordInfo<'/reglement', '/reglement', Record<never, never>, Record<never, never>>,
  }
}
